---
language: python
services: docker
branches:
  only:
    - master
env:
  global:
    - ROLE_NAME: meabed.lets_encrypt_cname
    - REPO_NAME: ansible-role-lets-encrypt-cname
    # yamllint disable-line
    - secure: ac4uwY1+2BLiNjVF1ZXBvp07OIKsWQ62GeM9M/A0JydSqRwRIATApvnYmP1A0jI8ZrM0G5xQDkJb+Y6x7uCwUp1CaHj6qCAV+/w5uGrTP5P+WJBWdfnD0TK5sPUjvg28Y7X2OAHlKvpWOfgTHhFoB2XveAf0vKdZlAWfxuDlYSj8aWprDgPM/i54ti2jgSgFeUNnAUoqkiO8ms1qf/uHX09tBMO9aLw9Fm7Xn2zAW+71AaPl8JuyPOhezZMDmWz4CPJrqFkBBcD/Oe5wIEgMNUI206BvpLqCOIs72ypwuBeAcg/sxUaah1U42a2I8rf6WaFdGFNMkd7S/mDhCFuTfcaZ2/QF08jmaIdttao3t7mNDBRaF7rhgdTBWGg7TpxdLkMvkmhMfVq/lnbCh8bqpvBmIgsSXKquAXlmqqkHe+Pv27xE5BHhoxZmMmRWGz4BPq/REOpZu6Y41aS4bD9P+p56EkskLojpsfY+DIPqyFWDmGr4pFz55ek86lfI5iGcpK0+ysTKosDDMvmAh8WpZ5TGg3xuRL6ytUVZGl2S5PiadwQklrBmvvikKIy+iJSL22Zx4mR52FaMxT7JvJ9SImqTKEjX2ru3TLxqRbgJ5CzGLd2Tjp2lnUIzMsUW2M7vPG6pxfaZF0xFlMjr3fPrmh1ZjvqHTxhDnmhm5SHEFtE=
    # yamllint disable-line
    - secure: vuVaEzBfSKp9/70KwY7fv3nThZyaE2Wny39NIYdqZYTkE0g/I937ikkPhYd2sJ5pQJckgoOP2G7AgW4kt387cVRSUcb686bb3HLA5aE1DqoroyTLkqHJedMyha9SGLDKFXn9yIjOMs4HwNridZ6WwQH5/tE8iRXzyqTHRFu7P889pX3ScTJv/DfxOaIlWGhwpNm42gcVQ04LfxcwAUkFGrau8Dy51Tqj32GC76nKW6qNnPd+2jdTdx624Ab+9epIMQIn0RjYDVXon4Cujg0/iX+AlzgQAygxQiRDUGap27Hlu0klkMRc75gIB0Zo6n6CXl6QU25fLaU3Inx/pcQhJDl9fHhomWH0n1diK6/zcdAPSakOGSvNYt0ZYHl897KjymWrdhqbcVG+/7RrZKz+Bnye2MRuBcsZuC207QAwLpN2DuZp7vAqoUkzLSb8q8Cgn6d32UTudAaoYQYYHF69vvuMptyIG0dGK9i8+veeD2NVwS5d2ZRQM1PtBJZ86Lt1ZutTib/+Zu550MRCq7GVIH7mSaHpY+3DXZ3SuMO24Rt8shVUvM79uJZIU6bKVDFQAi/vQJasxD21t2up5F1e+QNjffbMtDQSwUhw2Wa2Mp+cnu6Y9Y+JaavzlGeBSfuIWrHac4ggvIyJbhD+HXzU+cGUvxDVKN5BwlLF85uqP1M=
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9
install:
  - pip install molecule docker
before_script:
  - cd ../
  - mv $REPO_NAME $ROLE_NAME
  - cd $ROLE_NAME
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
