---
- name: install the required dependencies (Debian)
  apt:
    name: "{{ packages }}"
    update_cache: true
    cache_valid_time: 604800
    allow_unauthenticated: true
  register: apt_res
  retries: 5
  until: apt_res is success
  vars:
    packages:
      - openssl

- name: install pyOpenSSL and boto
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    version: "{{ item.version | default(omit) }}"
  with_items:
    - name: pyOpenSSL
    - name: boto
    - name: enum34
    - name: ipaddress
    - name: cffi
